CREATE TABLE IF NOT EXISTS "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "email" varchar(100) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "profile_photo" varchar(255),
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50)
);

CREATE TABLE IF NOT EXISTS "States" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50)
);

CREATE TABLE IF NOT EXISTS "Tasks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(150),
  "description" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "due_date" timestamp,
  "priority" varchar(10),
  "category_id" int,
  "state_id" int,
  "supertask_id" int
);

CREATE TABLE IF NOT EXISTS "UserTask" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" int,
  "user_id" int,
  "assigned_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS "Comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" int,
  "user_id" int,
  "message" text,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS "Attachments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" int,
  "file_url" varchar(255),
  "uploaded_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

COMMENT ON COLUMN "Tasks"."priority" IS 'Low, Medium, High, Urgent';

ALTER TABLE "Tasks" ADD FOREIGN KEY ("category_id") REFERENCES "Categories" ("id");

ALTER TABLE "Tasks" ADD FOREIGN KEY ("state_id") REFERENCES "States" ("id");

ALTER TABLE "Tasks" ADD FOREIGN KEY ("supertask_id") REFERENCES "Tasks" ("id");

ALTER TABLE "UserTask" ADD FOREIGN KEY ("task_id") REFERENCES "Tasks" ("id");

ALTER TABLE "UserTask" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Comments" ADD FOREIGN KEY ("task_id") REFERENCES "Tasks" ("id");

ALTER TABLE "Comments" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Attachments" ADD FOREIGN KEY ("task_id") REFERENCES "Tasks" ("id");
